import 'package:house_of_challenge/models/user_model.dart';
import 'package:house_of_challenge/models/video_model.dart';
import 'package:house_of_challenge/models/challenge_model.dart';
import 'package:house_of_challenge/models/comment_model.dart';

class MockData {
  static final User currentUser = User(
    id: 'user_1',
    username: 'AlexChallenger',
    email: 'alex@challenge.com',
    profilePicture: 'https://i.pravatar.cc/150?img=1',
    bio: 'Dance enthusiast & Challenge lover 🎬',
    followers: 1250,
    following: 342,
    totalVotes: 450,
    challengesCompleted: 12,
    badges: ['🏆', '⭐', '🎯', '💯'],
    isVerified: true,
    createdAt: DateTime(2022, 6, 15),
    points: 4500,
  );

  static final List<User> sampleUsers = [
    User(
      id: 'user_2',
      username: 'DanceMaster',
      email: 'dancemr@challenge.com',
      profilePicture: 'https://i.pravatar.cc/150?img=2',
      bio: 'Professional dancer',
      followers: 5420,
      following: 234,
      totalVotes: 1200,
      challengesCompleted: 25,
      badges: ['🏆', '⭐', '🎯'],
      isVerified: true,
      createdAt: DateTime(2021, 3, 10),
      points: 8900,
    ),
    User(
      id: 'user_3',
      username: 'CreativeVibe',
      email: 'creative@challenge.com',
      profilePicture: 'https://i.pravatar.cc/150?img=3',
      bio: 'Artist and content creator',
      followers: 3210,
      following: 567,
      totalVotes: 890,
      challengesCompleted: 18,
      badges: ['⭐', '🎯'],
      isVerified: true,
      createdAt: DateTime(2022, 1, 20),
      points: 7200,
    ),
    User(
      id: 'user_4',
      username: 'FitnessChamp',
      email: 'fitness@challenge.com',
      profilePicture: 'https://i.pravatar.cc/150?img=4',
      bio: 'Fitness & workout challenges',
      followers: 4560,
      following: 345,
      totalVotes: 1500,
      challengesCompleted: 30,
      badges: ['🏆', '⭐', '🎯', '💯'],
      isVerified: true,
      createdAt: DateTime(2020, 12, 5),
      points: 9500,
    ),
  ];

  static final List<Video> sampleVideos = [
    Video(
      id: 'vid_1',
      title: 'Epic Dance Performance',
      description: 'Amazing contemporary dance routine combining traditional and modern styles. This performance showcases creativity and technical skill.',
      videoUrl: 'https://sample-videos.com/video1.mp4',
      thumbnailUrl: 'https://picsum.photos/300/200?random=1',
      creatorId: 'user_2',
      creatorName: 'DanceMaster',
      creatorAvatar: 'https://i.pravatar.cc/150?img=2',
      challengeTitle: 'Dance Revolution 2024',
      category: 'Dance',
      views: 15420,
      likes: 3200,
      votes: 890,
      likedBy: ['user_1', 'user_3'],
      votedBy: ['user_1', 'user_4', 'user_3'],
      createdAt: DateTime.now().subtract(Duration(hours: 2)),
      duration: Duration(minutes: 3, seconds: 45),
      isLiked: true,
      isVoted: true,
      comments: 245,
    ),
    Video(
      id: 'vid_2',
      title: 'Creative Art Sculpture',
      description: 'Time-lapse of creating an amazing sculpture using recycled materials. Environmental art challenge entry.',
      videoUrl: 'https://sample-videos.com/video2.mp4',
      thumbnailUrl: 'https://picsum.photos/300/200?random=2',
      creatorId: 'user_3',
      creatorName: 'CreativeVibe',
      creatorAvatar: 'https://i.pravatar.cc/150?img=3',
      challengeTitle: 'Eco Art Challenge',
      category: 'Art',
      views: 8950,
      likes: 2100,
      votes: 650,
      likedBy: ['user_1'],
      votedBy: ['user_1', 'user_2'],
      createdAt: DateTime.now().subtract(Duration(hours: 5)),
      duration: Duration(minutes: 2, seconds: 30),
      isVoted: true,
      comments: 156,
    ),
    Video(
      id: 'vid_3',
      title: 'Intense Workout Challenge',
      description: 'Complete 30-minute intense workout routine. Perfect for building strength and endurance. Follow along for best results!',
      videoUrl: 'https://sample-videos.com/video3.mp4',
      thumbnailUrl: 'https://picsum.photos/300/200?random=3',
      creatorId: 'user_4',
      creatorName: 'FitnessChamp',
      creatorAvatar: 'https://i.pravatar.cc/150?img=4',
      challengeTitle: '30-Day Fitness Revolution',
      category: 'Fitness',
      views: 22350,
      likes: 4500,
      votes: 1200,
      likedBy: [],
      votedBy: [],
      createdAt: DateTime.now().subtract(Duration(hours: 8)),
      duration: Duration(minutes: 30),
      comments: 389,
    ),
    Video(
      id: 'vid_4',
      title: 'Cooking Masterclass',
      description: 'Learn to cook an exotic dish in just 5 minutes. Culinary challenge entry with amazing presentation.',
      videoUrl: 'https://sample-videos.com/video4.mp4',
      thumbnailUrl: 'https://picsum.photos/300/200?random=4',
      creatorId: 'user_1',
      creatorName: 'AlexChallenger',
      creatorAvatar: 'https://i.pravatar.cc/150?img=1',
      challengeTitle: '5-Minute Meals',
      category: 'Cooking',
      views: 5600,
      likes: 1200,
      votes: 420,
      likedBy: ['user_2'],
      votedBy: ['user_2', 'user_3'],
      createdAt: DateTime.now().subtract(Duration(hours: 12)),
      duration: Duration(minutes: 5, seconds: 20),
      isVoted: false,
      comments: 98,
    ),
  ];

  static final List<Challenge> sampleChallenges = [
    Challenge(
      id: 'ch_1',
      title: 'Dance Revolution 2024',
      description: 'Show off your best dance moves! Submit your most creative dance performance.',
      imageUrl: 'https://picsum.photos/400/300?random=5',
      category: 'Dance',
      startDate: DateTime.now().subtract(Duration(days: 5)),
      endDate: DateTime.now().add(Duration(days: 10)),
      totalParticipants: 1247,
      totalSubmissions: 856,
      status: 'active',
      prizePool: 50000,
      rules: [
        'Video must be between 30 seconds and 5 minutes',
        'Original music or licensed content only',
        'No watermarks from other platforms',
      ],
    ),
    Challenge(
      id: 'ch_2',
      title: 'Eco Art Challenge',
      description: 'Create art using recycled or sustainable materials.',
      imageUrl: 'https://picsum.photos/400/300?random=6',
      category: 'Art',
      startDate: DateTime.now().subtract(Duration(days: 2)),
      endDate: DateTime.now().add(Duration(days: 15)),
      totalParticipants: 523,
      totalSubmissions: 312,
      status: 'active',
      prizePool: 30000,
      rules: [
        'Must use at least 50% recycled materials',
        'Time-lapse videos welcome',
        'Final piece must be clearly visible',
      ],
    ),
    Challenge(
      id: 'ch_3',
      title: '30-Day Fitness Revolution',
      description: 'Complete fitness challenges throughout the month.',
      imageUrl: 'https://picsum.photos/400/300?random=7',
      category: 'Fitness',
      startDate: DateTime.now().subtract(Duration(days: 10)),
      endDate: DateTime.now().add(Duration(days: 20)),
      totalParticipants: 2156,
      totalSubmissions: 1890,
      status: 'active',
      prizePool: 100000,
      rules: [
        'Daily submission required',
        'Proper form is essential',
        'Encourage others in comments',
      ],
    ),
  ];

  static final List<Comment> sampleComments = [
    Comment(
      id: 'cmt_1',
      userId: 'user_3',
      userName: 'CreativeVibe',
      userAvatar: 'https://i.pravatar.cc/150?img=3',
      text: 'Amazing performance! This is exactly what the challenge is about! 🔥',
      createdAt: DateTime.now().subtract(Duration(hours: 1)),
      likes: 45,
      replies: [],
    ),
    Comment(
      id: 'cmt_2',
      userId: 'user_4',
      userName: 'FitnessChamp',
      userAvatar: 'https://i.pravatar.cc/150?img=4',
      text: 'Love the creativity! Definitely voting for this! ⭐',
      createdAt: DateTime.now().subtract(Duration(hours: 2)),
      likes: 32,
      replies: [
        Comment(
          id: 'reply_1',
          userId: 'user_2',
          userName: 'DanceMaster',
          userAvatar: 'https://i.pravatar.cc/150?img=2',
          text: 'Thank you so much! 😊',
          createdAt: DateTime.now().subtract(Duration(hours: 1, minutes: 30)),
          likes: 12,
          replies: [],
        ),
      ],
    ),
  ];
}
